import React, { FunctionComponent } from 'react';
import { AntdIconProps as IconProps } from '@ant-design/icons/lib/components/AntdIcon';
import { IconBaseProps } from '@ant-design/icons/lib/components/Icon';
import { CustomIconOptions } from '@ant-design/icons/lib/components/IconFont';
import * as AntDesignIcons from '@ant-design/icons';
// noinspection SpellCheckingInspection
const iconMapper = {
  "AccountBookFilled": AntDesignIcons.AccountBookFilled,
  "AccountBookOutlined": AntDesignIcons.AccountBookOutlined,
  "AccountBookTwoTone": AntDesignIcons.AccountBookTwoTone,
  "AimOutlined": AntDesignIcons.AimOutlined,
  "AlertFilled": AntDesignIcons.AlertFilled,
  "AlertOutlined": AntDesignIcons.AlertOutlined,
  "AlertTwoTone": AntDesignIcons.AlertTwoTone,
  "AlibabaOutlined": AntDesignIcons.AlibabaOutlined,
  "AlignCenterOutlined": AntDesignIcons.AlignCenterOutlined,
  "AlignLeftOutlined": AntDesignIcons.AlignLeftOutlined,
  "AlignRightOutlined": AntDesignIcons.AlignRightOutlined,
  "AlipayCircleFilled": AntDesignIcons.AlipayCircleFilled,
  "AlipayCircleOutlined": AntDesignIcons.AlipayCircleOutlined,
  "AlipayOutlined": AntDesignIcons.AlipayOutlined,
  "AlipaySquareFilled": AntDesignIcons.AlipaySquareFilled,
  "AliwangwangFilled": AntDesignIcons.AliwangwangFilled,
  "AliwangwangOutlined": AntDesignIcons.AliwangwangOutlined,
  "AliyunOutlined": AntDesignIcons.AliyunOutlined,
  "AmazonCircleFilled": AntDesignIcons.AmazonCircleFilled,
  "AmazonOutlined": AntDesignIcons.AmazonOutlined,
  "AmazonSquareFilled": AntDesignIcons.AmazonSquareFilled,
  "AndroidFilled": AntDesignIcons.AndroidFilled,
  "AndroidOutlined": AntDesignIcons.AndroidOutlined,
  "AntCloudOutlined": AntDesignIcons.AntCloudOutlined,
  "AntDesignOutlined": AntDesignIcons.AntDesignOutlined,
  "ApartmentOutlined": AntDesignIcons.ApartmentOutlined,
  "ApiFilled": AntDesignIcons.ApiFilled,
  "ApiOutlined": AntDesignIcons.ApiOutlined,
  "ApiTwoTone": AntDesignIcons.ApiTwoTone,
  "AppleFilled": AntDesignIcons.AppleFilled,
  "AppleOutlined": AntDesignIcons.AppleOutlined,
  "AppstoreAddOutlined": AntDesignIcons.AppstoreAddOutlined,
  "AppstoreFilled": AntDesignIcons.AppstoreFilled,
  "AppstoreOutlined": AntDesignIcons.AppstoreOutlined,
  "AppstoreTwoTone": AntDesignIcons.AppstoreTwoTone,
  "AreaChartOutlined": AntDesignIcons.AreaChartOutlined,
  "ArrowDownOutlined": AntDesignIcons.ArrowDownOutlined,
  "ArrowLeftOutlined": AntDesignIcons.ArrowLeftOutlined,
  "ArrowRightOutlined": AntDesignIcons.ArrowRightOutlined,
  "ArrowsAltOutlined": AntDesignIcons.ArrowsAltOutlined,
  "ArrowUpOutlined": AntDesignIcons.ArrowUpOutlined,
  "AudioFilled": AntDesignIcons.AudioFilled,
  "AudioMutedOutlined": AntDesignIcons.AudioMutedOutlined,
  "AudioOutlined": AntDesignIcons.AudioOutlined,
  "AudioTwoTone": AntDesignIcons.AudioTwoTone,
  "AuditOutlined": AntDesignIcons.AuditOutlined,
  "BackwardFilled": AntDesignIcons.BackwardFilled,
  "BackwardOutlined": AntDesignIcons.BackwardOutlined,
  "BankFilled": AntDesignIcons.BankFilled,
  "BankOutlined": AntDesignIcons.BankOutlined,
  "BankTwoTone": AntDesignIcons.BankTwoTone,
  "BarChartOutlined": AntDesignIcons.BarChartOutlined,
  "BarcodeOutlined": AntDesignIcons.BarcodeOutlined,
  "BarsOutlined": AntDesignIcons.BarsOutlined,
  "BehanceCircleFilled": AntDesignIcons.BehanceCircleFilled,
  "BehanceOutlined": AntDesignIcons.BehanceOutlined,
  "BehanceSquareFilled": AntDesignIcons.BehanceSquareFilled,
  "BehanceSquareOutlined": AntDesignIcons.BehanceSquareOutlined,
  "BellFilled": AntDesignIcons.BellFilled,
  "BellOutlined": AntDesignIcons.BellOutlined,
  "BellTwoTone": AntDesignIcons.BellTwoTone,
  "BgColorsOutlined": AntDesignIcons.BgColorsOutlined,
  "BlockOutlined": AntDesignIcons.BlockOutlined,
  "BoldOutlined": AntDesignIcons.BoldOutlined,
  "BookFilled": AntDesignIcons.BookFilled,
  "BookOutlined": AntDesignIcons.BookOutlined,
  "BookTwoTone": AntDesignIcons.BookTwoTone,
  "BorderBottomOutlined": AntDesignIcons.BorderBottomOutlined,
  "BorderHorizontalOutlined": AntDesignIcons.BorderHorizontalOutlined,
  "BorderInnerOutlined": AntDesignIcons.BorderInnerOutlined,
  "BorderLeftOutlined": AntDesignIcons.BorderLeftOutlined,
  "BorderlessTableOutlined": AntDesignIcons.BorderlessTableOutlined,
  "BorderOuterOutlined": AntDesignIcons.BorderOuterOutlined,
  "BorderOutlined": AntDesignIcons.BorderOutlined,
  "BorderRightOutlined": AntDesignIcons.BorderRightOutlined,
  "BorderTopOutlined": AntDesignIcons.BorderTopOutlined,
  "BorderVerticleOutlined": AntDesignIcons.BorderVerticleOutlined,
  "BoxPlotFilled": AntDesignIcons.BoxPlotFilled,
  "BoxPlotOutlined": AntDesignIcons.BoxPlotOutlined,
  "BoxPlotTwoTone": AntDesignIcons.BoxPlotTwoTone,
  "BranchesOutlined": AntDesignIcons.BranchesOutlined,
  "BugFilled": AntDesignIcons.BugFilled,
  "BugOutlined": AntDesignIcons.BugOutlined,
  "BugTwoTone": AntDesignIcons.BugTwoTone,
  "BuildFilled": AntDesignIcons.BuildFilled,
  "BuildOutlined": AntDesignIcons.BuildOutlined,
  "BuildTwoTone": AntDesignIcons.BuildTwoTone,
  "BulbFilled": AntDesignIcons.BulbFilled,
  "BulbOutlined": AntDesignIcons.BulbOutlined,
  "BulbTwoTone": AntDesignIcons.BulbTwoTone,
  "CalculatorFilled": AntDesignIcons.CalculatorFilled,
  "CalculatorOutlined": AntDesignIcons.CalculatorOutlined,
  "CalculatorTwoTone": AntDesignIcons.CalculatorTwoTone,
  "CalendarFilled": AntDesignIcons.CalendarFilled,
  "CalendarOutlined": AntDesignIcons.CalendarOutlined,
  "CalendarTwoTone": AntDesignIcons.CalendarTwoTone,
  "CameraFilled": AntDesignIcons.CameraFilled,
  "CameraOutlined": AntDesignIcons.CameraOutlined,
  "CameraTwoTone": AntDesignIcons.CameraTwoTone,
  "CaretDownFilled": AntDesignIcons.CaretDownFilled,
  "CaretDownOutlined": AntDesignIcons.CaretDownOutlined,
  "CaretLeftFilled": AntDesignIcons.CaretLeftFilled,
  "CaretLeftOutlined": AntDesignIcons.CaretLeftOutlined,
  "CaretRightFilled": AntDesignIcons.CaretRightFilled,
  "CaretRightOutlined": AntDesignIcons.CaretRightOutlined,
  "CaretUpFilled": AntDesignIcons.CaretUpFilled,
  "CaretUpOutlined": AntDesignIcons.CaretUpOutlined,
  "CarFilled": AntDesignIcons.CarFilled,
  "CarOutlined": AntDesignIcons.CarOutlined,
  "CarryOutFilled": AntDesignIcons.CarryOutFilled,
  "CarryOutOutlined": AntDesignIcons.CarryOutOutlined,
  "CarryOutTwoTone": AntDesignIcons.CarryOutTwoTone,
  "CarTwoTone": AntDesignIcons.CarTwoTone,
  "CheckCircleFilled": AntDesignIcons.CheckCircleFilled,
  "CheckCircleOutlined": AntDesignIcons.CheckCircleOutlined,
  "CheckCircleTwoTone": AntDesignIcons.CheckCircleTwoTone,
  "CheckOutlined": AntDesignIcons.CheckOutlined,
  "CheckSquareFilled": AntDesignIcons.CheckSquareFilled,
  "CheckSquareOutlined": AntDesignIcons.CheckSquareOutlined,
  "CheckSquareTwoTone": AntDesignIcons.CheckSquareTwoTone,
  "ChromeFilled": AntDesignIcons.ChromeFilled,
  "ChromeOutlined": AntDesignIcons.ChromeOutlined,
  "CiCircleFilled": AntDesignIcons.CiCircleFilled,
  "CiCircleOutlined": AntDesignIcons.CiCircleOutlined,
  "CiCircleTwoTone": AntDesignIcons.CiCircleTwoTone,
  "CiOutlined": AntDesignIcons.CiOutlined,
  "CiTwoTone": AntDesignIcons.CiTwoTone,
  "ClearOutlined": AntDesignIcons.ClearOutlined,
  "ClockCircleFilled": AntDesignIcons.ClockCircleFilled,
  "ClockCircleOutlined": AntDesignIcons.ClockCircleOutlined,
  "ClockCircleTwoTone": AntDesignIcons.ClockCircleTwoTone,
  "CloseCircleFilled": AntDesignIcons.CloseCircleFilled,
  "CloseCircleOutlined": AntDesignIcons.CloseCircleOutlined,
  "CloseCircleTwoTone": AntDesignIcons.CloseCircleTwoTone,
  "CloseOutlined": AntDesignIcons.CloseOutlined,
  "CloseSquareFilled": AntDesignIcons.CloseSquareFilled,
  "CloseSquareOutlined": AntDesignIcons.CloseSquareOutlined,
  "CloseSquareTwoTone": AntDesignIcons.CloseSquareTwoTone,
  "CloudDownloadOutlined": AntDesignIcons.CloudDownloadOutlined,
  "CloudFilled": AntDesignIcons.CloudFilled,
  "CloudOutlined": AntDesignIcons.CloudOutlined,
  "CloudServerOutlined": AntDesignIcons.CloudServerOutlined,
  "CloudSyncOutlined": AntDesignIcons.CloudSyncOutlined,
  "CloudTwoTone": AntDesignIcons.CloudTwoTone,
  "CloudUploadOutlined": AntDesignIcons.CloudUploadOutlined,
  "ClusterOutlined": AntDesignIcons.ClusterOutlined,
  "CodeFilled": AntDesignIcons.CodeFilled,
  "CodeOutlined": AntDesignIcons.CodeOutlined,
  "CodepenCircleFilled": AntDesignIcons.CodepenCircleFilled,
  "CodepenCircleOutlined": AntDesignIcons.CodepenCircleOutlined,
  "CodepenOutlined": AntDesignIcons.CodepenOutlined,
  "CodepenSquareFilled": AntDesignIcons.CodepenSquareFilled,
  "CodeSandboxCircleFilled": AntDesignIcons.CodeSandboxCircleFilled,
  "CodeSandboxOutlined": AntDesignIcons.CodeSandboxOutlined,
  "CodeSandboxSquareFilled": AntDesignIcons.CodeSandboxSquareFilled,
  "CodeTwoTone": AntDesignIcons.CodeTwoTone,
  "CoffeeOutlined": AntDesignIcons.CoffeeOutlined,
  "ColumnHeightOutlined": AntDesignIcons.ColumnHeightOutlined,
  "ColumnWidthOutlined": AntDesignIcons.ColumnWidthOutlined,
  "CommentOutlined": AntDesignIcons.CommentOutlined,
  "CompassFilled": AntDesignIcons.CompassFilled,
  "CompassOutlined": AntDesignIcons.CompassOutlined,
  "CompassTwoTone": AntDesignIcons.CompassTwoTone,
  "CompressOutlined": AntDesignIcons.CompressOutlined,
  "ConsoleSqlOutlined": AntDesignIcons.ConsoleSqlOutlined,
  "ContactsFilled": AntDesignIcons.ContactsFilled,
  "ContactsOutlined": AntDesignIcons.ContactsOutlined,
  "ContactsTwoTone": AntDesignIcons.ContactsTwoTone,
  "ContainerFilled": AntDesignIcons.ContainerFilled,
  "ContainerOutlined": AntDesignIcons.ContainerOutlined,
  "ContainerTwoTone": AntDesignIcons.ContainerTwoTone,
  "ControlFilled": AntDesignIcons.ControlFilled,
  "ControlOutlined": AntDesignIcons.ControlOutlined,
  "ControlTwoTone": AntDesignIcons.ControlTwoTone,
  "CopyFilled": AntDesignIcons.CopyFilled,
  "CopyOutlined": AntDesignIcons.CopyOutlined,
  "CopyrightCircleFilled": AntDesignIcons.CopyrightCircleFilled,
  "CopyrightCircleOutlined": AntDesignIcons.CopyrightCircleOutlined,
  "CopyrightCircleTwoTone": AntDesignIcons.CopyrightCircleTwoTone,
  "CopyrightOutlined": AntDesignIcons.CopyrightOutlined,
  "CopyrightTwoTone": AntDesignIcons.CopyrightTwoTone,
  "CopyTwoTone": AntDesignIcons.CopyTwoTone,
  "CreditCardFilled": AntDesignIcons.CreditCardFilled,
  "CreditCardOutlined": AntDesignIcons.CreditCardOutlined,
  "CreditCardTwoTone": AntDesignIcons.CreditCardTwoTone,
  "CrownFilled": AntDesignIcons.CrownFilled,
  "CrownOutlined": AntDesignIcons.CrownOutlined,
  "CrownTwoTone": AntDesignIcons.CrownTwoTone,
  "CustomerServiceFilled": AntDesignIcons.CustomerServiceFilled,
  "CustomerServiceOutlined": AntDesignIcons.CustomerServiceOutlined,
  "CustomerServiceTwoTone": AntDesignIcons.CustomerServiceTwoTone,
  "DashboardFilled": AntDesignIcons.DashboardFilled,
  "DashboardOutlined": AntDesignIcons.DashboardOutlined,
  "DashboardTwoTone": AntDesignIcons.DashboardTwoTone,
  "DashOutlined": AntDesignIcons.DashOutlined,
  "DatabaseFilled": AntDesignIcons.DatabaseFilled,
  "DatabaseOutlined": AntDesignIcons.DatabaseOutlined,
  "DatabaseTwoTone": AntDesignIcons.DatabaseTwoTone,
  "DeleteColumnOutlined": AntDesignIcons.DeleteColumnOutlined,
  "DeleteFilled": AntDesignIcons.DeleteFilled,
  "DeleteOutlined": AntDesignIcons.DeleteOutlined,
  "DeleteRowOutlined": AntDesignIcons.DeleteRowOutlined,
  "DeleteTwoTone": AntDesignIcons.DeleteTwoTone,
  "DeliveredProcedureOutlined": AntDesignIcons.DeliveredProcedureOutlined,
  "DeploymentUnitOutlined": AntDesignIcons.DeploymentUnitOutlined,
  "DesktopOutlined": AntDesignIcons.DesktopOutlined,
  "DiffFilled": AntDesignIcons.DiffFilled,
  "DiffOutlined": AntDesignIcons.DiffOutlined,
  "DiffTwoTone": AntDesignIcons.DiffTwoTone,
  "DingdingOutlined": AntDesignIcons.DingdingOutlined,
  "DingtalkCircleFilled": AntDesignIcons.DingtalkCircleFilled,
  "DingtalkOutlined": AntDesignIcons.DingtalkOutlined,
  "DingtalkSquareFilled": AntDesignIcons.DingtalkSquareFilled,
  "DisconnectOutlined": AntDesignIcons.DisconnectOutlined,
  "DislikeFilled": AntDesignIcons.DislikeFilled,
  "DislikeOutlined": AntDesignIcons.DislikeOutlined,
  "DislikeTwoTone": AntDesignIcons.DislikeTwoTone,
  "DollarCircleFilled": AntDesignIcons.DollarCircleFilled,
  "DollarCircleOutlined": AntDesignIcons.DollarCircleOutlined,
  "DollarCircleTwoTone": AntDesignIcons.DollarCircleTwoTone,
  "DollarOutlined": AntDesignIcons.DollarOutlined,
  "DollarTwoTone": AntDesignIcons.DollarTwoTone,
  "DotChartOutlined": AntDesignIcons.DotChartOutlined,
  "DoubleLeftOutlined": AntDesignIcons.DoubleLeftOutlined,
  "DoubleRightOutlined": AntDesignIcons.DoubleRightOutlined,
  "DownCircleFilled": AntDesignIcons.DownCircleFilled,
  "DownCircleOutlined": AntDesignIcons.DownCircleOutlined,
  "DownCircleTwoTone": AntDesignIcons.DownCircleTwoTone,
  "DownloadOutlined": AntDesignIcons.DownloadOutlined,
  "DownOutlined": AntDesignIcons.DownOutlined,
  "DownSquareFilled": AntDesignIcons.DownSquareFilled,
  "DownSquareOutlined": AntDesignIcons.DownSquareOutlined,
  "DownSquareTwoTone": AntDesignIcons.DownSquareTwoTone,
  "DragOutlined": AntDesignIcons.DragOutlined,
  "DribbbleCircleFilled": AntDesignIcons.DribbbleCircleFilled,
  "DribbbleOutlined": AntDesignIcons.DribbbleOutlined,
  "DribbbleSquareFilled": AntDesignIcons.DribbbleSquareFilled,
  "DribbbleSquareOutlined": AntDesignIcons.DribbbleSquareOutlined,
  "DropboxCircleFilled": AntDesignIcons.DropboxCircleFilled,
  "DropboxOutlined": AntDesignIcons.DropboxOutlined,
  "DropboxSquareFilled": AntDesignIcons.DropboxSquareFilled,
  "EditFilled": AntDesignIcons.EditFilled,
  "EditOutlined": AntDesignIcons.EditOutlined,
  "EditTwoTone": AntDesignIcons.EditTwoTone,
  "EllipsisOutlined": AntDesignIcons.EllipsisOutlined,
  "EnterOutlined": AntDesignIcons.EnterOutlined,
  "EnvironmentFilled": AntDesignIcons.EnvironmentFilled,
  "EnvironmentOutlined": AntDesignIcons.EnvironmentOutlined,
  "EnvironmentTwoTone": AntDesignIcons.EnvironmentTwoTone,
  "EuroCircleFilled": AntDesignIcons.EuroCircleFilled,
  "EuroCircleOutlined": AntDesignIcons.EuroCircleOutlined,
  "EuroCircleTwoTone": AntDesignIcons.EuroCircleTwoTone,
  "EuroOutlined": AntDesignIcons.EuroOutlined,
  "EuroTwoTone": AntDesignIcons.EuroTwoTone,
  "ExceptionOutlined": AntDesignIcons.ExceptionOutlined,
  "ExclamationCircleFilled": AntDesignIcons.ExclamationCircleFilled,
  "ExclamationCircleOutlined": AntDesignIcons.ExclamationCircleOutlined,
  "ExclamationCircleTwoTone": AntDesignIcons.ExclamationCircleTwoTone,
  "ExclamationOutlined": AntDesignIcons.ExclamationOutlined,
  "ExpandAltOutlined": AntDesignIcons.ExpandAltOutlined,
  "ExpandOutlined": AntDesignIcons.ExpandOutlined,
  "ExperimentFilled": AntDesignIcons.ExperimentFilled,
  "ExperimentOutlined": AntDesignIcons.ExperimentOutlined,
  "ExperimentTwoTone": AntDesignIcons.ExperimentTwoTone,
  "ExportOutlined": AntDesignIcons.ExportOutlined,
  "EyeFilled": AntDesignIcons.EyeFilled,
  "EyeInvisibleFilled": AntDesignIcons.EyeInvisibleFilled,
  "EyeInvisibleOutlined": AntDesignIcons.EyeInvisibleOutlined,
  "EyeInvisibleTwoTone": AntDesignIcons.EyeInvisibleTwoTone,
  "EyeOutlined": AntDesignIcons.EyeOutlined,
  "EyeTwoTone": AntDesignIcons.EyeTwoTone,
  "FacebookFilled": AntDesignIcons.FacebookFilled,
  "FacebookOutlined": AntDesignIcons.FacebookOutlined,
  "FallOutlined": AntDesignIcons.FallOutlined,
  "FastBackwardFilled": AntDesignIcons.FastBackwardFilled,
  "FastBackwardOutlined": AntDesignIcons.FastBackwardOutlined,
  "FastForwardFilled": AntDesignIcons.FastForwardFilled,
  "FastForwardOutlined": AntDesignIcons.FastForwardOutlined,
  "FieldBinaryOutlined": AntDesignIcons.FieldBinaryOutlined,
  "FieldNumberOutlined": AntDesignIcons.FieldNumberOutlined,
  "FieldStringOutlined": AntDesignIcons.FieldStringOutlined,
  "FieldTimeOutlined": AntDesignIcons.FieldTimeOutlined,
  "FileAddFilled": AntDesignIcons.FileAddFilled,
  "FileAddOutlined": AntDesignIcons.FileAddOutlined,
  "FileAddTwoTone": AntDesignIcons.FileAddTwoTone,
  "FileDoneOutlined": AntDesignIcons.FileDoneOutlined,
  "FileExcelFilled": AntDesignIcons.FileExcelFilled,
  "FileExcelOutlined": AntDesignIcons.FileExcelOutlined,
  "FileExcelTwoTone": AntDesignIcons.FileExcelTwoTone,
  "FileExclamationFilled": AntDesignIcons.FileExclamationFilled,
  "FileExclamationOutlined": AntDesignIcons.FileExclamationOutlined,
  "FileExclamationTwoTone": AntDesignIcons.FileExclamationTwoTone,
  "FileFilled": AntDesignIcons.FileFilled,
  "FileGifOutlined": AntDesignIcons.FileGifOutlined,
  "FileImageFilled": AntDesignIcons.FileImageFilled,
  "FileImageOutlined": AntDesignIcons.FileImageOutlined,
  "FileImageTwoTone": AntDesignIcons.FileImageTwoTone,
  "FileJpgOutlined": AntDesignIcons.FileJpgOutlined,
  "FileMarkdownFilled": AntDesignIcons.FileMarkdownFilled,
  "FileMarkdownOutlined": AntDesignIcons.FileMarkdownOutlined,
  "FileMarkdownTwoTone": AntDesignIcons.FileMarkdownTwoTone,
  "FileOutlined": AntDesignIcons.FileOutlined,
  "FilePdfFilled": AntDesignIcons.FilePdfFilled,
  "FilePdfOutlined": AntDesignIcons.FilePdfOutlined,
  "FilePdfTwoTone": AntDesignIcons.FilePdfTwoTone,
  "FilePptFilled": AntDesignIcons.FilePptFilled,
  "FilePptOutlined": AntDesignIcons.FilePptOutlined,
  "FilePptTwoTone": AntDesignIcons.FilePptTwoTone,
  "FileProtectOutlined": AntDesignIcons.FileProtectOutlined,
  "FileSearchOutlined": AntDesignIcons.FileSearchOutlined,
  "FileSyncOutlined": AntDesignIcons.FileSyncOutlined,
  "FileTextFilled": AntDesignIcons.FileTextFilled,
  "FileTextOutlined": AntDesignIcons.FileTextOutlined,
  "FileTextTwoTone": AntDesignIcons.FileTextTwoTone,
  "FileTwoTone": AntDesignIcons.FileTwoTone,
  "FileUnknownFilled": AntDesignIcons.FileUnknownFilled,
  "FileUnknownOutlined": AntDesignIcons.FileUnknownOutlined,
  "FileUnknownTwoTone": AntDesignIcons.FileUnknownTwoTone,
  "FileWordFilled": AntDesignIcons.FileWordFilled,
  "FileWordOutlined": AntDesignIcons.FileWordOutlined,
  "FileWordTwoTone": AntDesignIcons.FileWordTwoTone,
  "FileZipFilled": AntDesignIcons.FileZipFilled,
  "FileZipOutlined": AntDesignIcons.FileZipOutlined,
  "FileZipTwoTone": AntDesignIcons.FileZipTwoTone,
  "FilterFilled": AntDesignIcons.FilterFilled,
  "FilterOutlined": AntDesignIcons.FilterOutlined,
  "FilterTwoTone": AntDesignIcons.FilterTwoTone,
  "FireFilled": AntDesignIcons.FireFilled,
  "FireOutlined": AntDesignIcons.FireOutlined,
  "FireTwoTone": AntDesignIcons.FireTwoTone,
  "FlagFilled": AntDesignIcons.FlagFilled,
  "FlagOutlined": AntDesignIcons.FlagOutlined,
  "FlagTwoTone": AntDesignIcons.FlagTwoTone,
  "FolderAddFilled": AntDesignIcons.FolderAddFilled,
  "FolderAddOutlined": AntDesignIcons.FolderAddOutlined,
  "FolderAddTwoTone": AntDesignIcons.FolderAddTwoTone,
  "FolderFilled": AntDesignIcons.FolderFilled,
  "FolderOpenFilled": AntDesignIcons.FolderOpenFilled,
  "FolderOpenOutlined": AntDesignIcons.FolderOpenOutlined,
  "FolderOpenTwoTone": AntDesignIcons.FolderOpenTwoTone,
  "FolderOutlined": AntDesignIcons.FolderOutlined,
  "FolderTwoTone": AntDesignIcons.FolderTwoTone,
  "FolderViewOutlined": AntDesignIcons.FolderViewOutlined,
  "FontColorsOutlined": AntDesignIcons.FontColorsOutlined,
  "FontSizeOutlined": AntDesignIcons.FontSizeOutlined,
  "ForkOutlined": AntDesignIcons.ForkOutlined,
  "FormatPainterFilled": AntDesignIcons.FormatPainterFilled,
  "FormatPainterOutlined": AntDesignIcons.FormatPainterOutlined,
  "FormOutlined": AntDesignIcons.FormOutlined,
  "ForwardFilled": AntDesignIcons.ForwardFilled,
  "ForwardOutlined": AntDesignIcons.ForwardOutlined,
  "FrownFilled": AntDesignIcons.FrownFilled,
  "FrownOutlined": AntDesignIcons.FrownOutlined,
  "FrownTwoTone": AntDesignIcons.FrownTwoTone,
  "FullscreenExitOutlined": AntDesignIcons.FullscreenExitOutlined,
  "FullscreenOutlined": AntDesignIcons.FullscreenOutlined,
  "FunctionOutlined": AntDesignIcons.FunctionOutlined,
  "FundFilled": AntDesignIcons.FundFilled,
  "FundOutlined": AntDesignIcons.FundOutlined,
  "FundProjectionScreenOutlined": AntDesignIcons.FundProjectionScreenOutlined,
  "FundTwoTone": AntDesignIcons.FundTwoTone,
  "FundViewOutlined": AntDesignIcons.FundViewOutlined,
  "FunnelPlotFilled": AntDesignIcons.FunnelPlotFilled,
  "FunnelPlotOutlined": AntDesignIcons.FunnelPlotOutlined,
  "FunnelPlotTwoTone": AntDesignIcons.FunnelPlotTwoTone,
  "GatewayOutlined": AntDesignIcons.GatewayOutlined,
  "GifOutlined": AntDesignIcons.GifOutlined,
  "GiftFilled": AntDesignIcons.GiftFilled,
  "GiftOutlined": AntDesignIcons.GiftOutlined,
  "GiftTwoTone": AntDesignIcons.GiftTwoTone,
  "GithubFilled": AntDesignIcons.GithubFilled,
  "GithubOutlined": AntDesignIcons.GithubOutlined,
  "GitlabFilled": AntDesignIcons.GitlabFilled,
  "GitlabOutlined": AntDesignIcons.GitlabOutlined,
  "GlobalOutlined": AntDesignIcons.GlobalOutlined,
  "GoldenFilled": AntDesignIcons.GoldenFilled,
  "GoldFilled": AntDesignIcons.GoldFilled,
  "GoldOutlined": AntDesignIcons.GoldOutlined,
  "GoldTwoTone": AntDesignIcons.GoldTwoTone,
  "GoogleCircleFilled": AntDesignIcons.GoogleCircleFilled,
  "GoogleOutlined": AntDesignIcons.GoogleOutlined,
  "GooglePlusCircleFilled": AntDesignIcons.GooglePlusCircleFilled,
  "GooglePlusOutlined": AntDesignIcons.GooglePlusOutlined,
  "GooglePlusSquareFilled": AntDesignIcons.GooglePlusSquareFilled,
  "GoogleSquareFilled": AntDesignIcons.GoogleSquareFilled,
  "GroupOutlined": AntDesignIcons.GroupOutlined,
  "HddFilled": AntDesignIcons.HddFilled,
  "HddOutlined": AntDesignIcons.HddOutlined,
  "HddTwoTone": AntDesignIcons.HddTwoTone,
  "HeartFilled": AntDesignIcons.HeartFilled,
  "HeartOutlined": AntDesignIcons.HeartOutlined,
  "HeartTwoTone": AntDesignIcons.HeartTwoTone,
  "HeatMapOutlined": AntDesignIcons.HeatMapOutlined,
  "HighlightFilled": AntDesignIcons.HighlightFilled,
  "HighlightOutlined": AntDesignIcons.HighlightOutlined,
  "HighlightTwoTone": AntDesignIcons.HighlightTwoTone,
  "HistoryOutlined": AntDesignIcons.HistoryOutlined,
  "HomeFilled": AntDesignIcons.HomeFilled,
  "HomeOutlined": AntDesignIcons.HomeOutlined,
  "HomeTwoTone": AntDesignIcons.HomeTwoTone,
  "HourglassFilled": AntDesignIcons.HourglassFilled,
  "HourglassOutlined": AntDesignIcons.HourglassOutlined,
  "HourglassTwoTone": AntDesignIcons.HourglassTwoTone,
  "Html5Filled": AntDesignIcons.Html5Filled,
  "Html5Outlined": AntDesignIcons.Html5Outlined,
  "Html5TwoTone": AntDesignIcons.Html5TwoTone,
  "IdcardFilled": AntDesignIcons.IdcardFilled,
  "IdcardOutlined": AntDesignIcons.IdcardOutlined,
  "IdcardTwoTone": AntDesignIcons.IdcardTwoTone,
  "IeCircleFilled": AntDesignIcons.IeCircleFilled,
  "IeOutlined": AntDesignIcons.IeOutlined,
  "IeSquareFilled": AntDesignIcons.IeSquareFilled,
  "ImportOutlined": AntDesignIcons.ImportOutlined,
  "InboxOutlined": AntDesignIcons.InboxOutlined,
  "InfoCircleFilled": AntDesignIcons.InfoCircleFilled,
  "InfoCircleOutlined": AntDesignIcons.InfoCircleOutlined,
  "InfoCircleTwoTone": AntDesignIcons.InfoCircleTwoTone,
  "InfoOutlined": AntDesignIcons.InfoOutlined,
  "InsertRowAboveOutlined": AntDesignIcons.InsertRowAboveOutlined,
  "InsertRowBelowOutlined": AntDesignIcons.InsertRowBelowOutlined,
  "InsertRowLeftOutlined": AntDesignIcons.InsertRowLeftOutlined,
  "InsertRowRightOutlined": AntDesignIcons.InsertRowRightOutlined,
  "InstagramFilled": AntDesignIcons.InstagramFilled,
  "InstagramOutlined": AntDesignIcons.InstagramOutlined,
  "InsuranceFilled": AntDesignIcons.InsuranceFilled,
  "InsuranceOutlined": AntDesignIcons.InsuranceOutlined,
  "InsuranceTwoTone": AntDesignIcons.InsuranceTwoTone,
  "InteractionFilled": AntDesignIcons.InteractionFilled,
  "InteractionOutlined": AntDesignIcons.InteractionOutlined,
  "InteractionTwoTone": AntDesignIcons.InteractionTwoTone,
  "IssuesCloseOutlined": AntDesignIcons.IssuesCloseOutlined,
  "ItalicOutlined": AntDesignIcons.ItalicOutlined,
  "KeyOutlined": AntDesignIcons.KeyOutlined,
  "LaptopOutlined": AntDesignIcons.LaptopOutlined,
  "LayoutFilled": AntDesignIcons.LayoutFilled,
  "LayoutOutlined": AntDesignIcons.LayoutOutlined,
  "LayoutTwoTone": AntDesignIcons.LayoutTwoTone,
  "LeftCircleFilled": AntDesignIcons.LeftCircleFilled,
  "LeftCircleOutlined": AntDesignIcons.LeftCircleOutlined,
  "LeftCircleTwoTone": AntDesignIcons.LeftCircleTwoTone,
  "LeftOutlined": AntDesignIcons.LeftOutlined,
  "LeftSquareFilled": AntDesignIcons.LeftSquareFilled,
  "LeftSquareOutlined": AntDesignIcons.LeftSquareOutlined,
  "LeftSquareTwoTone": AntDesignIcons.LeftSquareTwoTone,
  "LikeFilled": AntDesignIcons.LikeFilled,
  "LikeOutlined": AntDesignIcons.LikeOutlined,
  "LikeTwoTone": AntDesignIcons.LikeTwoTone,
  "LineChartOutlined": AntDesignIcons.LineChartOutlined,
  "LineHeightOutlined": AntDesignIcons.LineHeightOutlined,
  "LineOutlined": AntDesignIcons.LineOutlined,
  "LinkedinFilled": AntDesignIcons.LinkedinFilled,
  "LinkedinOutlined": AntDesignIcons.LinkedinOutlined,
  "LinkOutlined": AntDesignIcons.LinkOutlined,
  "Loading3QuartersOutlined": AntDesignIcons.Loading3QuartersOutlined,
  "LoadingOutlined": AntDesignIcons.LoadingOutlined,
  "LockFilled": AntDesignIcons.LockFilled,
  "LockOutlined": AntDesignIcons.LockOutlined,
  "LockTwoTone": AntDesignIcons.LockTwoTone,
  "LoginOutlined": AntDesignIcons.LoginOutlined,
  "LogoutOutlined": AntDesignIcons.LogoutOutlined,
  "MacCommandFilled": AntDesignIcons.MacCommandFilled,
  "MacCommandOutlined": AntDesignIcons.MacCommandOutlined,
  "MailFilled": AntDesignIcons.MailFilled,
  "MailOutlined": AntDesignIcons.MailOutlined,
  "MailTwoTone": AntDesignIcons.MailTwoTone,
  "ManOutlined": AntDesignIcons.ManOutlined,
  "MedicineBoxFilled": AntDesignIcons.MedicineBoxFilled,
  "MedicineBoxOutlined": AntDesignIcons.MedicineBoxOutlined,
  "MedicineBoxTwoTone": AntDesignIcons.MedicineBoxTwoTone,
  "MediumCircleFilled": AntDesignIcons.MediumCircleFilled,
  "MediumOutlined": AntDesignIcons.MediumOutlined,
  "MediumSquareFilled": AntDesignIcons.MediumSquareFilled,
  "MediumWorkmarkOutlined": AntDesignIcons.MediumWorkmarkOutlined,
  "MehFilled": AntDesignIcons.MehFilled,
  "MehOutlined": AntDesignIcons.MehOutlined,
  "MehTwoTone": AntDesignIcons.MehTwoTone,
  "MenuFoldOutlined": AntDesignIcons.MenuFoldOutlined,
  "MenuOutlined": AntDesignIcons.MenuOutlined,
  "MenuUnfoldOutlined": AntDesignIcons.MenuUnfoldOutlined,
  "MergeCellsOutlined": AntDesignIcons.MergeCellsOutlined,
  "MessageFilled": AntDesignIcons.MessageFilled,
  "MessageOutlined": AntDesignIcons.MessageOutlined,
  "MessageTwoTone": AntDesignIcons.MessageTwoTone,
  "MinusCircleFilled": AntDesignIcons.MinusCircleFilled,
  "MinusCircleOutlined": AntDesignIcons.MinusCircleOutlined,
  "MinusCircleTwoTone": AntDesignIcons.MinusCircleTwoTone,
  "MinusOutlined": AntDesignIcons.MinusOutlined,
  "MinusSquareFilled": AntDesignIcons.MinusSquareFilled,
  "MinusSquareOutlined": AntDesignIcons.MinusSquareOutlined,
  "MinusSquareTwoTone": AntDesignIcons.MinusSquareTwoTone,
  "MobileFilled": AntDesignIcons.MobileFilled,
  "MobileOutlined": AntDesignIcons.MobileOutlined,
  "MobileTwoTone": AntDesignIcons.MobileTwoTone,
  "MoneyCollectFilled": AntDesignIcons.MoneyCollectFilled,
  "MoneyCollectOutlined": AntDesignIcons.MoneyCollectOutlined,
  "MoneyCollectTwoTone": AntDesignIcons.MoneyCollectTwoTone,
  "MonitorOutlined": AntDesignIcons.MonitorOutlined,
  "MoreOutlined": AntDesignIcons.MoreOutlined,
  "NodeCollapseOutlined": AntDesignIcons.NodeCollapseOutlined,
  "NodeExpandOutlined": AntDesignIcons.NodeExpandOutlined,
  "NodeIndexOutlined": AntDesignIcons.NodeIndexOutlined,
  "NotificationFilled": AntDesignIcons.NotificationFilled,
  "NotificationOutlined": AntDesignIcons.NotificationOutlined,
  "NotificationTwoTone": AntDesignIcons.NotificationTwoTone,
  "NumberOutlined": AntDesignIcons.NumberOutlined,
  "OneToOneOutlined": AntDesignIcons.OneToOneOutlined,
  "OrderedListOutlined": AntDesignIcons.OrderedListOutlined,
  "PaperClipOutlined": AntDesignIcons.PaperClipOutlined,
  "PartitionOutlined": AntDesignIcons.PartitionOutlined,
  "PauseCircleFilled": AntDesignIcons.PauseCircleFilled,
  "PauseCircleOutlined": AntDesignIcons.PauseCircleOutlined,
  "PauseCircleTwoTone": AntDesignIcons.PauseCircleTwoTone,
  "PauseOutlined": AntDesignIcons.PauseOutlined,
  "PayCircleFilled": AntDesignIcons.PayCircleFilled,
  "PayCircleOutlined": AntDesignIcons.PayCircleOutlined,
  "PercentageOutlined": AntDesignIcons.PercentageOutlined,
  "PhoneFilled": AntDesignIcons.PhoneFilled,
  "PhoneOutlined": AntDesignIcons.PhoneOutlined,
  "PhoneTwoTone": AntDesignIcons.PhoneTwoTone,
  "PicCenterOutlined": AntDesignIcons.PicCenterOutlined,
  "PicLeftOutlined": AntDesignIcons.PicLeftOutlined,
  "PicRightOutlined": AntDesignIcons.PicRightOutlined,
  "PictureFilled": AntDesignIcons.PictureFilled,
  "PictureOutlined": AntDesignIcons.PictureOutlined,
  "PictureTwoTone": AntDesignIcons.PictureTwoTone,
  "PieChartFilled": AntDesignIcons.PieChartFilled,
  "PieChartOutlined": AntDesignIcons.PieChartOutlined,
  "PieChartTwoTone": AntDesignIcons.PieChartTwoTone,
  "PlayCircleFilled": AntDesignIcons.PlayCircleFilled,
  "PlayCircleOutlined": AntDesignIcons.PlayCircleOutlined,
  "PlayCircleTwoTone": AntDesignIcons.PlayCircleTwoTone,
  "PlaySquareFilled": AntDesignIcons.PlaySquareFilled,
  "PlaySquareOutlined": AntDesignIcons.PlaySquareOutlined,
  "PlaySquareTwoTone": AntDesignIcons.PlaySquareTwoTone,
  "PlusCircleFilled": AntDesignIcons.PlusCircleFilled,
  "PlusCircleOutlined": AntDesignIcons.PlusCircleOutlined,
  "PlusCircleTwoTone": AntDesignIcons.PlusCircleTwoTone,
  "PlusOutlined": AntDesignIcons.PlusOutlined,
  "PlusSquareFilled": AntDesignIcons.PlusSquareFilled,
  "PlusSquareOutlined": AntDesignIcons.PlusSquareOutlined,
  "PlusSquareTwoTone": AntDesignIcons.PlusSquareTwoTone,
  "PoundCircleFilled": AntDesignIcons.PoundCircleFilled,
  "PoundCircleOutlined": AntDesignIcons.PoundCircleOutlined,
  "PoundCircleTwoTone": AntDesignIcons.PoundCircleTwoTone,
  "PoundOutlined": AntDesignIcons.PoundOutlined,
  "PoweroffOutlined": AntDesignIcons.PoweroffOutlined,
  "PrinterFilled": AntDesignIcons.PrinterFilled,
  "PrinterOutlined": AntDesignIcons.PrinterOutlined,
  "PrinterTwoTone": AntDesignIcons.PrinterTwoTone,
  "ProfileFilled": AntDesignIcons.ProfileFilled,
  "ProfileOutlined": AntDesignIcons.ProfileOutlined,
  "ProfileTwoTone": AntDesignIcons.ProfileTwoTone,
  "ProjectFilled": AntDesignIcons.ProjectFilled,
  "ProjectOutlined": AntDesignIcons.ProjectOutlined,
  "ProjectTwoTone": AntDesignIcons.ProjectTwoTone,
  "PropertySafetyFilled": AntDesignIcons.PropertySafetyFilled,
  "PropertySafetyOutlined": AntDesignIcons.PropertySafetyOutlined,
  "PropertySafetyTwoTone": AntDesignIcons.PropertySafetyTwoTone,
  "PullRequestOutlined": AntDesignIcons.PullRequestOutlined,
  "PushpinFilled": AntDesignIcons.PushpinFilled,
  "PushpinOutlined": AntDesignIcons.PushpinOutlined,
  "PushpinTwoTone": AntDesignIcons.PushpinTwoTone,
  "QqCircleFilled": AntDesignIcons.QqCircleFilled,
  "QqOutlined": AntDesignIcons.QqOutlined,
  "QqSquareFilled": AntDesignIcons.QqSquareFilled,
  "QrcodeOutlined": AntDesignIcons.QrcodeOutlined,
  "QuestionCircleFilled": AntDesignIcons.QuestionCircleFilled,
  "QuestionCircleOutlined": AntDesignIcons.QuestionCircleOutlined,
  "QuestionCircleTwoTone": AntDesignIcons.QuestionCircleTwoTone,
  "QuestionOutlined": AntDesignIcons.QuestionOutlined,
  "RadarChartOutlined": AntDesignIcons.RadarChartOutlined,
  "RadiusBottomleftOutlined": AntDesignIcons.RadiusBottomleftOutlined,
  "RadiusBottomrightOutlined": AntDesignIcons.RadiusBottomrightOutlined,
  "RadiusSettingOutlined": AntDesignIcons.RadiusSettingOutlined,
  "RadiusUpleftOutlined": AntDesignIcons.RadiusUpleftOutlined,
  "RadiusUprightOutlined": AntDesignIcons.RadiusUprightOutlined,
  "ReadFilled": AntDesignIcons.ReadFilled,
  "ReadOutlined": AntDesignIcons.ReadOutlined,
  "ReconciliationFilled": AntDesignIcons.ReconciliationFilled,
  "ReconciliationOutlined": AntDesignIcons.ReconciliationOutlined,
  "ReconciliationTwoTone": AntDesignIcons.ReconciliationTwoTone,
  "RedditCircleFilled": AntDesignIcons.RedditCircleFilled,
  "RedditOutlined": AntDesignIcons.RedditOutlined,
  "RedditSquareFilled": AntDesignIcons.RedditSquareFilled,
  "RedEnvelopeFilled": AntDesignIcons.RedEnvelopeFilled,
  "RedEnvelopeOutlined": AntDesignIcons.RedEnvelopeOutlined,
  "RedEnvelopeTwoTone": AntDesignIcons.RedEnvelopeTwoTone,
  "RedoOutlined": AntDesignIcons.RedoOutlined,
  "ReloadOutlined": AntDesignIcons.ReloadOutlined,
  "RestFilled": AntDesignIcons.RestFilled,
  "RestOutlined": AntDesignIcons.RestOutlined,
  "RestTwoTone": AntDesignIcons.RestTwoTone,
  "RetweetOutlined": AntDesignIcons.RetweetOutlined,
  "RightCircleFilled": AntDesignIcons.RightCircleFilled,
  "RightCircleOutlined": AntDesignIcons.RightCircleOutlined,
  "RightCircleTwoTone": AntDesignIcons.RightCircleTwoTone,
  "RightOutlined": AntDesignIcons.RightOutlined,
  "RightSquareFilled": AntDesignIcons.RightSquareFilled,
  "RightSquareOutlined": AntDesignIcons.RightSquareOutlined,
  "RightSquareTwoTone": AntDesignIcons.RightSquareTwoTone,
  "RiseOutlined": AntDesignIcons.RiseOutlined,
  "RobotFilled": AntDesignIcons.RobotFilled,
  "RobotOutlined": AntDesignIcons.RobotOutlined,
  "RocketFilled": AntDesignIcons.RocketFilled,
  "RocketOutlined": AntDesignIcons.RocketOutlined,
  "RocketTwoTone": AntDesignIcons.RocketTwoTone,
  "RollbackOutlined": AntDesignIcons.RollbackOutlined,
  "RotateLeftOutlined": AntDesignIcons.RotateLeftOutlined,
  "RotateRightOutlined": AntDesignIcons.RotateRightOutlined,
  "SafetyCertificateFilled": AntDesignIcons.SafetyCertificateFilled,
  "SafetyCertificateOutlined": AntDesignIcons.SafetyCertificateOutlined,
  "SafetyCertificateTwoTone": AntDesignIcons.SafetyCertificateTwoTone,
  "SafetyOutlined": AntDesignIcons.SafetyOutlined,
  "SaveFilled": AntDesignIcons.SaveFilled,
  "SaveOutlined": AntDesignIcons.SaveOutlined,
  "SaveTwoTone": AntDesignIcons.SaveTwoTone,
  "ScanOutlined": AntDesignIcons.ScanOutlined,
  "ScheduleFilled": AntDesignIcons.ScheduleFilled,
  "ScheduleOutlined": AntDesignIcons.ScheduleOutlined,
  "ScheduleTwoTone": AntDesignIcons.ScheduleTwoTone,
  "ScissorOutlined": AntDesignIcons.ScissorOutlined,
  "SearchOutlined": AntDesignIcons.SearchOutlined,
  "SecurityScanFilled": AntDesignIcons.SecurityScanFilled,
  "SecurityScanOutlined": AntDesignIcons.SecurityScanOutlined,
  "SecurityScanTwoTone": AntDesignIcons.SecurityScanTwoTone,
  "SelectOutlined": AntDesignIcons.SelectOutlined,
  "SendOutlined": AntDesignIcons.SendOutlined,
  "SettingFilled": AntDesignIcons.SettingFilled,
  "SettingOutlined": AntDesignIcons.SettingOutlined,
  "SettingTwoTone": AntDesignIcons.SettingTwoTone,
  "ShakeOutlined": AntDesignIcons.ShakeOutlined,
  "ShareAltOutlined": AntDesignIcons.ShareAltOutlined,
  "ShopFilled": AntDesignIcons.ShopFilled,
  "ShopOutlined": AntDesignIcons.ShopOutlined,
  "ShoppingCartOutlined": AntDesignIcons.ShoppingCartOutlined,
  "ShoppingFilled": AntDesignIcons.ShoppingFilled,
  "ShoppingOutlined": AntDesignIcons.ShoppingOutlined,
  "ShoppingTwoTone": AntDesignIcons.ShoppingTwoTone,
  "ShopTwoTone": AntDesignIcons.ShopTwoTone,
  "ShrinkOutlined": AntDesignIcons.ShrinkOutlined,
  "SignalFilled": AntDesignIcons.SignalFilled,
  "SisternodeOutlined": AntDesignIcons.SisternodeOutlined,
  "SketchCircleFilled": AntDesignIcons.SketchCircleFilled,
  "SketchOutlined": AntDesignIcons.SketchOutlined,
  "SketchSquareFilled": AntDesignIcons.SketchSquareFilled,
  "SkinFilled": AntDesignIcons.SkinFilled,
  "SkinOutlined": AntDesignIcons.SkinOutlined,
  "SkinTwoTone": AntDesignIcons.SkinTwoTone,
  "SkypeFilled": AntDesignIcons.SkypeFilled,
  "SkypeOutlined": AntDesignIcons.SkypeOutlined,
  "SlackCircleFilled": AntDesignIcons.SlackCircleFilled,
  "SlackOutlined": AntDesignIcons.SlackOutlined,
  "SlackSquareFilled": AntDesignIcons.SlackSquareFilled,
  "SlackSquareOutlined": AntDesignIcons.SlackSquareOutlined,
  "SlidersFilled": AntDesignIcons.SlidersFilled,
  "SlidersOutlined": AntDesignIcons.SlidersOutlined,
  "SlidersTwoTone": AntDesignIcons.SlidersTwoTone,
  "SmallDashOutlined": AntDesignIcons.SmallDashOutlined,
  "SmileFilled": AntDesignIcons.SmileFilled,
  "SmileOutlined": AntDesignIcons.SmileOutlined,
  "SmileTwoTone": AntDesignIcons.SmileTwoTone,
  "SnippetsFilled": AntDesignIcons.SnippetsFilled,
  "SnippetsOutlined": AntDesignIcons.SnippetsOutlined,
  "SnippetsTwoTone": AntDesignIcons.SnippetsTwoTone,
  "SolutionOutlined": AntDesignIcons.SolutionOutlined,
  "SortAscendingOutlined": AntDesignIcons.SortAscendingOutlined,
  "SortDescendingOutlined": AntDesignIcons.SortDescendingOutlined,
  "SoundFilled": AntDesignIcons.SoundFilled,
  "SoundOutlined": AntDesignIcons.SoundOutlined,
  "SoundTwoTone": AntDesignIcons.SoundTwoTone,
  "SplitCellsOutlined": AntDesignIcons.SplitCellsOutlined,
  "StarFilled": AntDesignIcons.StarFilled,
  "StarOutlined": AntDesignIcons.StarOutlined,
  "StarTwoTone": AntDesignIcons.StarTwoTone,
  "StepBackwardFilled": AntDesignIcons.StepBackwardFilled,
  "StepBackwardOutlined": AntDesignIcons.StepBackwardOutlined,
  "StepForwardFilled": AntDesignIcons.StepForwardFilled,
  "StepForwardOutlined": AntDesignIcons.StepForwardOutlined,
  "StockOutlined": AntDesignIcons.StockOutlined,
  "StopFilled": AntDesignIcons.StopFilled,
  "StopOutlined": AntDesignIcons.StopOutlined,
  "StopTwoTone": AntDesignIcons.StopTwoTone,
  "StrikethroughOutlined": AntDesignIcons.StrikethroughOutlined,
  "SubnodeOutlined": AntDesignIcons.SubnodeOutlined,
  "SwapLeftOutlined": AntDesignIcons.SwapLeftOutlined,
  "SwapOutlined": AntDesignIcons.SwapOutlined,
  "SwapRightOutlined": AntDesignIcons.SwapRightOutlined,
  "SwitcherFilled": AntDesignIcons.SwitcherFilled,
  "SwitcherOutlined": AntDesignIcons.SwitcherOutlined,
  "SwitcherTwoTone": AntDesignIcons.SwitcherTwoTone,
  "SyncOutlined": AntDesignIcons.SyncOutlined,
  "TableOutlined": AntDesignIcons.TableOutlined,
  "TabletFilled": AntDesignIcons.TabletFilled,
  "TabletOutlined": AntDesignIcons.TabletOutlined,
  "TabletTwoTone": AntDesignIcons.TabletTwoTone,
  "TagFilled": AntDesignIcons.TagFilled,
  "TagOutlined": AntDesignIcons.TagOutlined,
  "TagsFilled": AntDesignIcons.TagsFilled,
  "TagsOutlined": AntDesignIcons.TagsOutlined,
  "TagsTwoTone": AntDesignIcons.TagsTwoTone,
  "TagTwoTone": AntDesignIcons.TagTwoTone,
  "TaobaoCircleFilled": AntDesignIcons.TaobaoCircleFilled,
  "TaobaoCircleOutlined": AntDesignIcons.TaobaoCircleOutlined,
  "TaobaoOutlined": AntDesignIcons.TaobaoOutlined,
  "TaobaoSquareFilled": AntDesignIcons.TaobaoSquareFilled,
  "TeamOutlined": AntDesignIcons.TeamOutlined,
  "ThunderboltFilled": AntDesignIcons.ThunderboltFilled,
  "ThunderboltOutlined": AntDesignIcons.ThunderboltOutlined,
  "ThunderboltTwoTone": AntDesignIcons.ThunderboltTwoTone,
  "ToolFilled": AntDesignIcons.ToolFilled,
  "ToolOutlined": AntDesignIcons.ToolOutlined,
  "ToolTwoTone": AntDesignIcons.ToolTwoTone,
  "ToTopOutlined": AntDesignIcons.ToTopOutlined,
  "TrademarkCircleFilled": AntDesignIcons.TrademarkCircleFilled,
  "TrademarkCircleOutlined": AntDesignIcons.TrademarkCircleOutlined,
  "TrademarkCircleTwoTone": AntDesignIcons.TrademarkCircleTwoTone,
  "TrademarkOutlined": AntDesignIcons.TrademarkOutlined,
  "TransactionOutlined": AntDesignIcons.TransactionOutlined,
  "TranslationOutlined": AntDesignIcons.TranslationOutlined,
  "TrophyFilled": AntDesignIcons.TrophyFilled,
  "TrophyOutlined": AntDesignIcons.TrophyOutlined,
  "TrophyTwoTone": AntDesignIcons.TrophyTwoTone,
  "TwitterCircleFilled": AntDesignIcons.TwitterCircleFilled,
  "TwitterOutlined": AntDesignIcons.TwitterOutlined,
  "TwitterSquareFilled": AntDesignIcons.TwitterSquareFilled,
  "UnderlineOutlined": AntDesignIcons.UnderlineOutlined,
  "UndoOutlined": AntDesignIcons.UndoOutlined,
  "UngroupOutlined": AntDesignIcons.UngroupOutlined,
  "UnlockFilled": AntDesignIcons.UnlockFilled,
  "UnlockOutlined": AntDesignIcons.UnlockOutlined,
  "UnlockTwoTone": AntDesignIcons.UnlockTwoTone,
  "UnorderedListOutlined": AntDesignIcons.UnorderedListOutlined,
  "UpCircleFilled": AntDesignIcons.UpCircleFilled,
  "UpCircleOutlined": AntDesignIcons.UpCircleOutlined,
  "UpCircleTwoTone": AntDesignIcons.UpCircleTwoTone,
  "UploadOutlined": AntDesignIcons.UploadOutlined,
  "UpOutlined": AntDesignIcons.UpOutlined,
  "UpSquareFilled": AntDesignIcons.UpSquareFilled,
  "UpSquareOutlined": AntDesignIcons.UpSquareOutlined,
  "UpSquareTwoTone": AntDesignIcons.UpSquareTwoTone,
  "UsbFilled": AntDesignIcons.UsbFilled,
  "UsbOutlined": AntDesignIcons.UsbOutlined,
  "UsbTwoTone": AntDesignIcons.UsbTwoTone,
  "UserAddOutlined": AntDesignIcons.UserAddOutlined,
  "UserDeleteOutlined": AntDesignIcons.UserDeleteOutlined,
  "UsergroupAddOutlined": AntDesignIcons.UsergroupAddOutlined,
  "UsergroupDeleteOutlined": AntDesignIcons.UsergroupDeleteOutlined,
  "UserOutlined": AntDesignIcons.UserOutlined,
  "UserSwitchOutlined": AntDesignIcons.UserSwitchOutlined,
  "VerifiedOutlined": AntDesignIcons.VerifiedOutlined,
  "VerticalAlignBottomOutlined": AntDesignIcons.VerticalAlignBottomOutlined,
  "VerticalAlignMiddleOutlined": AntDesignIcons.VerticalAlignMiddleOutlined,
  "VerticalAlignTopOutlined": AntDesignIcons.VerticalAlignTopOutlined,
  "VerticalLeftOutlined": AntDesignIcons.VerticalLeftOutlined,
  "VerticalRightOutlined": AntDesignIcons.VerticalRightOutlined,
  "VideoCameraAddOutlined": AntDesignIcons.VideoCameraAddOutlined,
  "VideoCameraFilled": AntDesignIcons.VideoCameraFilled,
  "VideoCameraOutlined": AntDesignIcons.VideoCameraOutlined,
  "VideoCameraTwoTone": AntDesignIcons.VideoCameraTwoTone,
  "WalletFilled": AntDesignIcons.WalletFilled,
  "WalletOutlined": AntDesignIcons.WalletOutlined,
  "WalletTwoTone": AntDesignIcons.WalletTwoTone,
  "WarningFilled": AntDesignIcons.WarningFilled,
  "WarningOutlined": AntDesignIcons.WarningOutlined,
  "WarningTwoTone": AntDesignIcons.WarningTwoTone,
  "WechatFilled": AntDesignIcons.WechatFilled,
  "WechatOutlined": AntDesignIcons.WechatOutlined,
  "WeiboCircleFilled": AntDesignIcons.WeiboCircleFilled,
  "WeiboCircleOutlined": AntDesignIcons.WeiboCircleOutlined,
  "WeiboOutlined": AntDesignIcons.WeiboOutlined,
  "WeiboSquareFilled": AntDesignIcons.WeiboSquareFilled,
  "WeiboSquareOutlined": AntDesignIcons.WeiboSquareOutlined,
  "WhatsAppOutlined": AntDesignIcons.WhatsAppOutlined,
  "WifiOutlined": AntDesignIcons.WifiOutlined,
  "WindowsFilled": AntDesignIcons.WindowsFilled,
  "WindowsOutlined": AntDesignIcons.WindowsOutlined,
  "WomanOutlined": AntDesignIcons.WomanOutlined,
  "YahooFilled": AntDesignIcons.YahooFilled,
  "YahooOutlined": AntDesignIcons.YahooOutlined,
  "YoutubeFilled": AntDesignIcons.YoutubeFilled,
  "YoutubeOutlined": AntDesignIcons.YoutubeOutlined,
  "YuqueFilled": AntDesignIcons.YuqueFilled,
  "YuqueOutlined": AntDesignIcons.YuqueOutlined,
  "ZhihuCircleFilled": AntDesignIcons.ZhihuCircleFilled,
  "ZhihuOutlined": AntDesignIcons.ZhihuOutlined,
  "ZhihuSquareFilled": AntDesignIcons.ZhihuSquareFilled,
  "ZoomInOutlined": AntDesignIcons.ZoomInOutlined,
  "ZoomOutOutlined": AntDesignIcons.ZoomOutOutlined,
};
// noinspection SpellCheckingInspection
export type AntdIconName = "AccountBookFilled" | "AccountBookOutlined" | "AccountBookTwoTone" | "AimOutlined" | "AlertFilled" | "AlertOutlined" |
  "AlertTwoTone" | "AlibabaOutlined" | "AlignCenterOutlined" | "AlignLeftOutlined" | "AlignRightOutlined" | "AlipayCircleFilled" |
  "AlipayCircleOutlined" | "AlipayOutlined" | "AlipaySquareFilled" | "AliwangwangFilled" | "AliwangwangOutlined" | "AliyunOutlined" |
  "AmazonCircleFilled" | "AmazonOutlined" | "AmazonSquareFilled" | "AndroidFilled" | "AndroidOutlined" | "AntCloudOutlined" |
  "AntDesignOutlined" | "ApartmentOutlined" | "ApiFilled" | "ApiOutlined" | "ApiTwoTone" | "AppleFilled" |
  "AppleOutlined" | "AppstoreAddOutlined" | "AppstoreFilled" | "AppstoreOutlined" | "AppstoreTwoTone" | "AreaChartOutlined" |
  "ArrowDownOutlined" | "ArrowLeftOutlined" | "ArrowRightOutlined" | "ArrowsAltOutlined" | "ArrowUpOutlined" | "AudioFilled" |
  "AudioMutedOutlined" | "AudioOutlined" | "AudioTwoTone" | "AuditOutlined" | "BackwardFilled" | "BackwardOutlined" |
  "BankFilled" | "BankOutlined" | "BankTwoTone" | "BarChartOutlined" | "BarcodeOutlined" | "BarsOutlined" |
  "BehanceCircleFilled" | "BehanceOutlined" | "BehanceSquareFilled" | "BehanceSquareOutlined" | "BellFilled" | "BellOutlined" |
  "BellTwoTone" | "BgColorsOutlined" | "BlockOutlined" | "BoldOutlined" | "BookFilled" | "BookOutlined" |
  "BookTwoTone" | "BorderBottomOutlined" | "BorderHorizontalOutlined" | "BorderInnerOutlined" | "BorderLeftOutlined" | "BorderlessTableOutlined" |
  "BorderOuterOutlined" | "BorderOutlined" | "BorderRightOutlined" | "BorderTopOutlined" | "BorderVerticleOutlined" | "BoxPlotFilled" |
  "BoxPlotOutlined" | "BoxPlotTwoTone" | "BranchesOutlined" | "BugFilled" | "BugOutlined" | "BugTwoTone" |
  "BuildFilled" | "BuildOutlined" | "BuildTwoTone" | "BulbFilled" | "BulbOutlined" | "BulbTwoTone" |
  "CalculatorFilled" | "CalculatorOutlined" | "CalculatorTwoTone" | "CalendarFilled" | "CalendarOutlined" | "CalendarTwoTone" |
  "CameraFilled" | "CameraOutlined" | "CameraTwoTone" | "CaretDownFilled" | "CaretDownOutlined" | "CaretLeftFilled" |
  "CaretLeftOutlined" | "CaretRightFilled" | "CaretRightOutlined" | "CaretUpFilled" | "CaretUpOutlined" | "CarFilled" |
  "CarOutlined" | "CarryOutFilled" | "CarryOutOutlined" | "CarryOutTwoTone" | "CarTwoTone" | "CheckCircleFilled" |
  "CheckCircleOutlined" | "CheckCircleTwoTone" | "CheckOutlined" | "CheckSquareFilled" | "CheckSquareOutlined" | "CheckSquareTwoTone" |
  "ChromeFilled" | "ChromeOutlined" | "CiCircleFilled" | "CiCircleOutlined" | "CiCircleTwoTone" | "CiOutlined" |
  "CiTwoTone" | "ClearOutlined" | "ClockCircleFilled" | "ClockCircleOutlined" | "ClockCircleTwoTone" | "CloseCircleFilled" |
  "CloseCircleOutlined" | "CloseCircleTwoTone" | "CloseOutlined" | "CloseSquareFilled" | "CloseSquareOutlined" | "CloseSquareTwoTone" |
  "CloudDownloadOutlined" | "CloudFilled" | "CloudOutlined" | "CloudServerOutlined" | "CloudSyncOutlined" | "CloudTwoTone" |
  "CloudUploadOutlined" | "ClusterOutlined" | "CodeFilled" | "CodeOutlined" | "CodepenCircleFilled" | "CodepenCircleOutlined" |
  "CodepenOutlined" | "CodepenSquareFilled" | "CodeSandboxCircleFilled" | "CodeSandboxOutlined" | "CodeSandboxSquareFilled" | "CodeTwoTone" |
  "CoffeeOutlined" | "ColumnHeightOutlined" | "ColumnWidthOutlined" | "CommentOutlined" | "CompassFilled" | "CompassOutlined" |
  "CompassTwoTone" | "CompressOutlined" | "ConsoleSqlOutlined" | "ContactsFilled" | "ContactsOutlined" | "ContactsTwoTone" |
  "ContainerFilled" | "ContainerOutlined" | "ContainerTwoTone" | "ControlFilled" | "ControlOutlined" | "ControlTwoTone" |
  "CopyFilled" | "CopyOutlined" | "CopyrightCircleFilled" | "CopyrightCircleOutlined" | "CopyrightCircleTwoTone" | "CopyrightOutlined" |
  "CopyrightTwoTone" | "CopyTwoTone" | "CreditCardFilled" | "CreditCardOutlined" | "CreditCardTwoTone" | "CrownFilled" |
  "CrownOutlined" | "CrownTwoTone" | "CustomerServiceFilled" | "CustomerServiceOutlined" | "CustomerServiceTwoTone" | "DashboardFilled" |
  "DashboardOutlined" | "DashboardTwoTone" | "DashOutlined" | "DatabaseFilled" | "DatabaseOutlined" | "DatabaseTwoTone" |
  "DeleteColumnOutlined" | "DeleteFilled" | "DeleteOutlined" | "DeleteRowOutlined" | "DeleteTwoTone" | "DeliveredProcedureOutlined" |
  "DeploymentUnitOutlined" | "DesktopOutlined" | "DiffFilled" | "DiffOutlined" | "DiffTwoTone" | "DingdingOutlined" |
  "DingtalkCircleFilled" | "DingtalkOutlined" | "DingtalkSquareFilled" | "DisconnectOutlined" | "DislikeFilled" | "DislikeOutlined" |
  "DislikeTwoTone" | "DollarCircleFilled" | "DollarCircleOutlined" | "DollarCircleTwoTone" | "DollarOutlined" | "DollarTwoTone" |
  "DotChartOutlined" | "DoubleLeftOutlined" | "DoubleRightOutlined" | "DownCircleFilled" | "DownCircleOutlined" | "DownCircleTwoTone" |
  "DownloadOutlined" | "DownOutlined" | "DownSquareFilled" | "DownSquareOutlined" | "DownSquareTwoTone" | "DragOutlined" |
  "DribbbleCircleFilled" | "DribbbleOutlined" | "DribbbleSquareFilled" | "DribbbleSquareOutlined" | "DropboxCircleFilled" | "DropboxOutlined" |
  "DropboxSquareFilled" | "EditFilled" | "EditOutlined" | "EditTwoTone" | "EllipsisOutlined" | "EnterOutlined" |
  "EnvironmentFilled" | "EnvironmentOutlined" | "EnvironmentTwoTone" | "EuroCircleFilled" | "EuroCircleOutlined" | "EuroCircleTwoTone" |
  "EuroOutlined" | "EuroTwoTone" | "ExceptionOutlined" | "ExclamationCircleFilled" | "ExclamationCircleOutlined" | "ExclamationCircleTwoTone" |
  "ExclamationOutlined" | "ExpandAltOutlined" | "ExpandOutlined" | "ExperimentFilled" | "ExperimentOutlined" | "ExperimentTwoTone" |
  "ExportOutlined" | "EyeFilled" | "EyeInvisibleFilled" | "EyeInvisibleOutlined" | "EyeInvisibleTwoTone" | "EyeOutlined" |
  "EyeTwoTone" | "FacebookFilled" | "FacebookOutlined" | "FallOutlined" | "FastBackwardFilled" | "FastBackwardOutlined" |
  "FastForwardFilled" | "FastForwardOutlined" | "FieldBinaryOutlined" | "FieldNumberOutlined" | "FieldStringOutlined" | "FieldTimeOutlined" |
  "FileAddFilled" | "FileAddOutlined" | "FileAddTwoTone" | "FileDoneOutlined" | "FileExcelFilled" | "FileExcelOutlined" |
  "FileExcelTwoTone" | "FileExclamationFilled" | "FileExclamationOutlined" | "FileExclamationTwoTone" | "FileFilled" | "FileGifOutlined" |
  "FileImageFilled" | "FileImageOutlined" | "FileImageTwoTone" | "FileJpgOutlined" | "FileMarkdownFilled" | "FileMarkdownOutlined" |
  "FileMarkdownTwoTone" | "FileOutlined" | "FilePdfFilled" | "FilePdfOutlined" | "FilePdfTwoTone" | "FilePptFilled" |
  "FilePptOutlined" | "FilePptTwoTone" | "FileProtectOutlined" | "FileSearchOutlined" | "FileSyncOutlined" | "FileTextFilled" |
  "FileTextOutlined" | "FileTextTwoTone" | "FileTwoTone" | "FileUnknownFilled" | "FileUnknownOutlined" | "FileUnknownTwoTone" |
  "FileWordFilled" | "FileWordOutlined" | "FileWordTwoTone" | "FileZipFilled" | "FileZipOutlined" | "FileZipTwoTone" |
  "FilterFilled" | "FilterOutlined" | "FilterTwoTone" | "FireFilled" | "FireOutlined" | "FireTwoTone" |
  "FlagFilled" | "FlagOutlined" | "FlagTwoTone" | "FolderAddFilled" | "FolderAddOutlined" | "FolderAddTwoTone" |
  "FolderFilled" | "FolderOpenFilled" | "FolderOpenOutlined" | "FolderOpenTwoTone" | "FolderOutlined" | "FolderTwoTone" |
  "FolderViewOutlined" | "FontColorsOutlined" | "FontSizeOutlined" | "ForkOutlined" | "FormatPainterFilled" | "FormatPainterOutlined" |
  "FormOutlined" | "ForwardFilled" | "ForwardOutlined" | "FrownFilled" | "FrownOutlined" | "FrownTwoTone" |
  "FullscreenExitOutlined" | "FullscreenOutlined" | "FunctionOutlined" | "FundFilled" | "FundOutlined" | "FundProjectionScreenOutlined" |
  "FundTwoTone" | "FundViewOutlined" | "FunnelPlotFilled" | "FunnelPlotOutlined" | "FunnelPlotTwoTone" | "GatewayOutlined" |
  "GifOutlined" | "GiftFilled" | "GiftOutlined" | "GiftTwoTone" | "GithubFilled" | "GithubOutlined" |
  "GitlabFilled" | "GitlabOutlined" | "GlobalOutlined" | "GoldenFilled" | "GoldFilled" | "GoldOutlined" |
  "GoldTwoTone" | "GoogleCircleFilled" | "GoogleOutlined" | "GooglePlusCircleFilled" | "GooglePlusOutlined" | "GooglePlusSquareFilled" |
  "GoogleSquareFilled" | "GroupOutlined" | "HddFilled" | "HddOutlined" | "HddTwoTone" | "HeartFilled" |
  "HeartOutlined" | "HeartTwoTone" | "HeatMapOutlined" | "HighlightFilled" | "HighlightOutlined" | "HighlightTwoTone" |
  "HistoryOutlined" | "HomeFilled" | "HomeOutlined" | "HomeTwoTone" | "HourglassFilled" | "HourglassOutlined" |
  "HourglassTwoTone" | "Html5Filled" | "Html5Outlined" | "Html5TwoTone" | "IdcardFilled" | "IdcardOutlined" |
  "IdcardTwoTone" | "IeCircleFilled" | "IeOutlined" | "IeSquareFilled" | "ImportOutlined" | "InboxOutlined" |
  "InfoCircleFilled" | "InfoCircleOutlined" | "InfoCircleTwoTone" | "InfoOutlined" | "InsertRowAboveOutlined" | "InsertRowBelowOutlined" |
  "InsertRowLeftOutlined" | "InsertRowRightOutlined" | "InstagramFilled" | "InstagramOutlined" | "InsuranceFilled" | "InsuranceOutlined" |
  "InsuranceTwoTone" | "InteractionFilled" | "InteractionOutlined" | "InteractionTwoTone" | "IssuesCloseOutlined" | "ItalicOutlined" |
  "KeyOutlined" | "LaptopOutlined" | "LayoutFilled" | "LayoutOutlined" | "LayoutTwoTone" | "LeftCircleFilled" |
  "LeftCircleOutlined" | "LeftCircleTwoTone" | "LeftOutlined" | "LeftSquareFilled" | "LeftSquareOutlined" | "LeftSquareTwoTone" |
  "LikeFilled" | "LikeOutlined" | "LikeTwoTone" | "LineChartOutlined" | "LineHeightOutlined" | "LineOutlined" |
  "LinkedinFilled" | "LinkedinOutlined" | "LinkOutlined" | "Loading3QuartersOutlined" | "LoadingOutlined" | "LockFilled" |
  "LockOutlined" | "LockTwoTone" | "LoginOutlined" | "LogoutOutlined" | "MacCommandFilled" | "MacCommandOutlined" |
  "MailFilled" | "MailOutlined" | "MailTwoTone" | "ManOutlined" | "MedicineBoxFilled" | "MedicineBoxOutlined" |
  "MedicineBoxTwoTone" | "MediumCircleFilled" | "MediumOutlined" | "MediumSquareFilled" | "MediumWorkmarkOutlined" | "MehFilled" |
  "MehOutlined" | "MehTwoTone" | "MenuFoldOutlined" | "MenuOutlined" | "MenuUnfoldOutlined" | "MergeCellsOutlined" |
  "MessageFilled" | "MessageOutlined" | "MessageTwoTone" | "MinusCircleFilled" | "MinusCircleOutlined" | "MinusCircleTwoTone" |
  "MinusOutlined" | "MinusSquareFilled" | "MinusSquareOutlined" | "MinusSquareTwoTone" | "MobileFilled" | "MobileOutlined" |
  "MobileTwoTone" | "MoneyCollectFilled" | "MoneyCollectOutlined" | "MoneyCollectTwoTone" | "MonitorOutlined" | "MoreOutlined" |
  "NodeCollapseOutlined" | "NodeExpandOutlined" | "NodeIndexOutlined" | "NotificationFilled" | "NotificationOutlined" | "NotificationTwoTone" |
  "NumberOutlined" | "OneToOneOutlined" | "OrderedListOutlined" | "PaperClipOutlined" | "PartitionOutlined" | "PauseCircleFilled" |
  "PauseCircleOutlined" | "PauseCircleTwoTone" | "PauseOutlined" | "PayCircleFilled" | "PayCircleOutlined" | "PercentageOutlined" |
  "PhoneFilled" | "PhoneOutlined" | "PhoneTwoTone" | "PicCenterOutlined" | "PicLeftOutlined" | "PicRightOutlined" |
  "PictureFilled" | "PictureOutlined" | "PictureTwoTone" | "PieChartFilled" | "PieChartOutlined" | "PieChartTwoTone" |
  "PlayCircleFilled" | "PlayCircleOutlined" | "PlayCircleTwoTone" | "PlaySquareFilled" | "PlaySquareOutlined" | "PlaySquareTwoTone" |
  "PlusCircleFilled" | "PlusCircleOutlined" | "PlusCircleTwoTone" | "PlusOutlined" | "PlusSquareFilled" | "PlusSquareOutlined" |
  "PlusSquareTwoTone" | "PoundCircleFilled" | "PoundCircleOutlined" | "PoundCircleTwoTone" | "PoundOutlined" | "PoweroffOutlined" |
  "PrinterFilled" | "PrinterOutlined" | "PrinterTwoTone" | "ProfileFilled" | "ProfileOutlined" | "ProfileTwoTone" |
  "ProjectFilled" | "ProjectOutlined" | "ProjectTwoTone" | "PropertySafetyFilled" | "PropertySafetyOutlined" | "PropertySafetyTwoTone" |
  "PullRequestOutlined" | "PushpinFilled" | "PushpinOutlined" | "PushpinTwoTone" | "QqCircleFilled" | "QqOutlined" |
  "QqSquareFilled" | "QrcodeOutlined" | "QuestionCircleFilled" | "QuestionCircleOutlined" | "QuestionCircleTwoTone" | "QuestionOutlined" |
  "RadarChartOutlined" | "RadiusBottomleftOutlined" | "RadiusBottomrightOutlined" | "RadiusSettingOutlined" | "RadiusUpleftOutlined" | "RadiusUprightOutlined" |
  "ReadFilled" | "ReadOutlined" | "ReconciliationFilled" | "ReconciliationOutlined" | "ReconciliationTwoTone" | "RedditCircleFilled" |
  "RedditOutlined" | "RedditSquareFilled" | "RedEnvelopeFilled" | "RedEnvelopeOutlined" | "RedEnvelopeTwoTone" | "RedoOutlined" |
  "ReloadOutlined" | "RestFilled" | "RestOutlined" | "RestTwoTone" | "RetweetOutlined" | "RightCircleFilled" |
  "RightCircleOutlined" | "RightCircleTwoTone" | "RightOutlined" | "RightSquareFilled" | "RightSquareOutlined" | "RightSquareTwoTone" |
  "RiseOutlined" | "RobotFilled" | "RobotOutlined" | "RocketFilled" | "RocketOutlined" | "RocketTwoTone" |
  "RollbackOutlined" | "RotateLeftOutlined" | "RotateRightOutlined" | "SafetyCertificateFilled" | "SafetyCertificateOutlined" | "SafetyCertificateTwoTone" |
  "SafetyOutlined" | "SaveFilled" | "SaveOutlined" | "SaveTwoTone" | "ScanOutlined" | "ScheduleFilled" |
  "ScheduleOutlined" | "ScheduleTwoTone" | "ScissorOutlined" | "SearchOutlined" | "SecurityScanFilled" | "SecurityScanOutlined" |
  "SecurityScanTwoTone" | "SelectOutlined" | "SendOutlined" | "SettingFilled" | "SettingOutlined" | "SettingTwoTone" |
  "ShakeOutlined" | "ShareAltOutlined" | "ShopFilled" | "ShopOutlined" | "ShoppingCartOutlined" | "ShoppingFilled" |
  "ShoppingOutlined" | "ShoppingTwoTone" | "ShopTwoTone" | "ShrinkOutlined" | "SignalFilled" | "SisternodeOutlined" |
  "SketchCircleFilled" | "SketchOutlined" | "SketchSquareFilled" | "SkinFilled" | "SkinOutlined" | "SkinTwoTone" |
  "SkypeFilled" | "SkypeOutlined" | "SlackCircleFilled" | "SlackOutlined" | "SlackSquareFilled" | "SlackSquareOutlined" |
  "SlidersFilled" | "SlidersOutlined" | "SlidersTwoTone" | "SmallDashOutlined" | "SmileFilled" | "SmileOutlined" |
  "SmileTwoTone" | "SnippetsFilled" | "SnippetsOutlined" | "SnippetsTwoTone" | "SolutionOutlined" | "SortAscendingOutlined" |
  "SortDescendingOutlined" | "SoundFilled" | "SoundOutlined" | "SoundTwoTone" | "SplitCellsOutlined" | "StarFilled" |
  "StarOutlined" | "StarTwoTone" | "StepBackwardFilled" | "StepBackwardOutlined" | "StepForwardFilled" | "StepForwardOutlined" |
  "StockOutlined" | "StopFilled" | "StopOutlined" | "StopTwoTone" | "StrikethroughOutlined" | "SubnodeOutlined" |
  "SwapLeftOutlined" | "SwapOutlined" | "SwapRightOutlined" | "SwitcherFilled" | "SwitcherOutlined" | "SwitcherTwoTone" |
  "SyncOutlined" | "TableOutlined" | "TabletFilled" | "TabletOutlined" | "TabletTwoTone" | "TagFilled" |
  "TagOutlined" | "TagsFilled" | "TagsOutlined" | "TagsTwoTone" | "TagTwoTone" | "TaobaoCircleFilled" |
  "TaobaoCircleOutlined" | "TaobaoOutlined" | "TaobaoSquareFilled" | "TeamOutlined" | "ThunderboltFilled" | "ThunderboltOutlined" |
  "ThunderboltTwoTone" | "ToolFilled" | "ToolOutlined" | "ToolTwoTone" | "ToTopOutlined" | "TrademarkCircleFilled" |
  "TrademarkCircleOutlined" | "TrademarkCircleTwoTone" | "TrademarkOutlined" | "TransactionOutlined" | "TranslationOutlined" | "TrophyFilled" |
  "TrophyOutlined" | "TrophyTwoTone" | "TwitterCircleFilled" | "TwitterOutlined" | "TwitterSquareFilled" | "UnderlineOutlined" |
  "UndoOutlined" | "UngroupOutlined" | "UnlockFilled" | "UnlockOutlined" | "UnlockTwoTone" | "UnorderedListOutlined" |
  "UpCircleFilled" | "UpCircleOutlined" | "UpCircleTwoTone" | "UploadOutlined" | "UpOutlined" | "UpSquareFilled" |
  "UpSquareOutlined" | "UpSquareTwoTone" | "UsbFilled" | "UsbOutlined" | "UsbTwoTone" | "UserAddOutlined" |
  "UserDeleteOutlined" | "UsergroupAddOutlined" | "UsergroupDeleteOutlined" | "UserOutlined" | "UserSwitchOutlined" | "VerifiedOutlined" |
  "VerticalAlignBottomOutlined" | "VerticalAlignMiddleOutlined" | "VerticalAlignTopOutlined" | "VerticalLeftOutlined" | "VerticalRightOutlined" | "VideoCameraAddOutlined" |
  "VideoCameraFilled" | "VideoCameraOutlined" | "VideoCameraTwoTone" | "WalletFilled" | "WalletOutlined" | "WalletTwoTone" |
  "WarningFilled" | "WarningOutlined" | "WarningTwoTone" | "WechatFilled" | "WechatOutlined" | "WeiboCircleFilled" |
  "WeiboCircleOutlined" | "WeiboOutlined" | "WeiboSquareFilled" | "WeiboSquareOutlined" | "WhatsAppOutlined" | "WifiOutlined" |
  "WindowsFilled" | "WindowsOutlined" | "WomanOutlined" | "YahooFilled" | "YahooOutlined" | "YoutubeFilled" |
  "YoutubeOutlined" | "YuqueFilled" | "YuqueOutlined" | "ZhihuCircleFilled" | "ZhihuOutlined" | "ZhihuSquareFilled" |
  "ZoomInOutlined" | "ZoomOutOutlined";

export interface AntdIconProps extends Omit<IconProps, "ref">, React.RefAttributes<HTMLSpanElement> {
  icon?: AntdIconName;
  type?: string;
}

const AntdIcon: FunctionComponent<AntdIconProps> = (props: AntdIconProps): React.ReactElement | null => {
  let Icon: any;
  if (props.icon) {
    Icon = iconMapper[props.icon];
  }
  if (!Icon && props.type) {
    Icon = iconMapper[props.type];
  }
  if (!Icon) {
    return null;
  }
  return (
    <Icon {...props} />
  );
};
export default AntdIcon;

export interface IconFontProps extends IconBaseProps {
  type: string;
}

export type AntdIconFont = FunctionComponent<IconFontProps>;
// noinspection JSUnusedGlobalSymbols
export const createIconFontCN = (options: CustomIconOptions): AntdIconFont => {
  return AntDesignIcons.createFromIconfontCN({ ...options });
};

// 代码使用 auto-generate.js 自动生成
